apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit
spec:
  selector:
    matchLabels:
      app: credit
  replicas: 1
  template:
    metadata:
      labels:
        app: credit
    spec:
      containers:
      - name: credit
        image: svizor/zoomcamp-model:hw10
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 9696
